janfelber/si-project

rocksolid-be/docker-compose.yaml
rocksolid-be/src/main/java/com/rocksolid/module/article.java
rocksolid-be/src/main/java/com/rocksolid/module/conference.java
rocksolid-be/src/main/java/com/rocksolid/module/form.java
rocksolid-be/src/main/java/com/rocksolid/module/recenzent.java
rocksolid-be/src/main/java/com/rocksolid/module/token.java
rocksolid-be/src/main/java/com/rocksolid/module/user.java
rocksolid-be/src/main/resources/application.properties

table modules

---

.idea/dataSources.xml

Docker file config

---

rocksolid-be/src/main/java/com/rocksolid/controller/UserController.java
rocksolid-be/src/main/java/com/rocksolid/service/UserService.java
rocksolid-be/src/main/java/com/rocksolid/service/UserServiceImpl.java

ROC-25 Optimize findAllUsers to reduce redundant nested information

ROC-25 Optimize findAllUsers to reduce redundant nested information

---

rocksolid-be/src/main/java/com/rocksolid/auth/AuthenticationService.java
rocksolid-be/src/main/java/com/rocksolid/auth/RegisterRequest.java

ROC-6 Users Roles - fix, register users will have student role

ROC-6 Users Roles - fix, register users will have student role

---

rocksolid-be/src/main/java/com/rocksolid/controller/UserController.java
rocksolid-be/src/main/java/com/rocksolid/dto/UserResponseDto.java
rocksolid-be/src/main/java/com/rocksolid/service/UserServiceImpl.java
rocksolid-fe/vue-project/src/views/UserDetailView.vue

ROC-30 Implement toggle button to set user role as Student or Reviewer

ROC-30 Implement toggle button to set user role as Student or Reviewer

---

rocksolid-be/src/main/java/com/rocksolid/auth/AuthenticationService.java
rocksolid-be/src/main/java/com/rocksolid/auth/RegisterRequest.java
rocksolid-fe/vue-project/src/views/RegisterView.vue

ROC-38 Register - name and surname

ROC-38 Register - name and surname

---

rocksolid-be/src/main/java/com/rocksolid/controller/UserController.java

ROC-33 filter admin in table

---

rocksolid-fe/.idea/inspectionProfiles/Project_Default.xml
rocksolid-fe/vue-project/src/views/StudentView.vue

ROC-12 Create demo upload form

ROC-12 Create demo upload form - new style

---

rocksolid-be/pom.xml
rocksolid-be/src/main/resources/application.properties
rocksolid-be/src/main/resources/db/migration/V1__Ignored_migration.sql

ROC-42 Import Flyway framework

---

rocksolid-fe/vue-project/src/views/AdminLayout.vue
rocksolid-fe/vue-project/src/views/AdminUsersView.vue

ROC-43 Admin page - searchable users table

ROC-43 Admin page - searchable users table

---

rocksolid-be/src/main/java/com/rocksolid/module/article.java
rocksolid-be/src/main/resources/application.properties
rocksolid-be/src/main/resources/db/migration/V2__ROC_41.sql

Create Article table migration

ROC 41 article table migration

---

rocksolid-be/src/main/java/com/rocksolid/auth/AuthenticationService.java
rocksolid-be/src/main/java/com/rocksolid/auth/EmailAlreadyExistsException.java
rocksolid-be/src/main/java/com/rocksolid/auth/GlobalExceptionHandler.java
rocksolid-fe/vue-project/src/views/RegisterView.vue

Prevent account creation with duplicate email addresses

Roc-46 Prevent account creation with duplicate email addresses

---

rocksolid-be/src/main/java/com/rocksolid/module/User.java
rocksolid-be/src/main/java/com/rocksolid/module/article.java
rocksolid-be/src/main/resources/db/migration/V3__ROC_32.sql

ROC-32 Article module

---

rocksolid-fe/vue-project/src/main.js
rocksolid-fe/vue-project/src/views/AdminLayout.vue
rocksolid-fe/vue-project/src/views/AdminUsersView.vue

ROC-36 Table css

---

rocksolid-be/src/main/java/com/rocksolid/controller/ConferenceController.java
rocksolid-be/src/main/java/com/rocksolid/dto/ConferenceRequestDto.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceService.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceServiceImpl.java

ROC-49 Admin page - create conference

ROC-49 Admin page - create conference

---

rocksolid-fe/vue-project/src/views/ConferenceView.vue

ROC-50 Admin page - create conference dialog window

ROC-50 Admin page - create conference dialog window

---

rocksolid-be/src/main/java/com/rocksolid/controller/ConferenceController.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceService.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceServiceImpl.java

ROC-51 Admin page - update conference data

ROC-51 Admin page - update conference data

---

rocksolid-fe/vue-project/src/views/ConferenceView.vue

ROC-52 Admin page - update conference data

ROC-52 Admin page - update conference data

---

rocksolid-fe/vue-project/src/views/AdminUsersView.vue
rocksolid-fe/vue-project/src/views/UserDetailView.vue

ROC-53 UserView delete selected user

ROC-53 UserView delete selected user

---

rocksolid-fe/vue-project/package-lock.json
rocksolid-fe/vue-project/package.json
rocksolid-fe/vue-project/src/main.js
rocksolid-fe/vue-project/src/views/AdminLayout.vue
rocksolid-fe/vue-project/src/views/UserDetailView.vue
rocksolid-fe/vue-project/yarn.lock

ROC-54 UserView css

---

rocksolid-fe/vue-project/src/views/ConferenceView.vue

ROC-55 Admin page - Conference alerts

ROC-55 Admin page - Conference alerts

---

rocksolid-be/src/main/java/com/rocksolid/controller/ConferenceController.java
rocksolid-be/src/main/java/com/rocksolid/repository/ConferenceRepository.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceService.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceServiceImpl.java
rocksolid-fe/vue-project/src/data/navBarData.js
rocksolid-fe/vue-project/src/router/index.js
rocksolid-fe/vue-project/src/views/ActiveConferences.vue

ROC 56 List of Active Conferences

---

rocksolid-be/src/main/java/com/rocksolid/auth/AuthenticationResponse.java
rocksolid-be/src/main/java/com/rocksolid/auth/AuthenticationService.java
rocksolid-fe/vue-project/src/views/LoginView.vue

ROC-34 Login-role layout

---

rocksolid-be/src/main/java/com/rocksolid/auth/CurrentUserService.java
rocksolid-be/src/main/java/com/rocksolid/controller/UserController.java
rocksolid-fe/vue-project/src/components/Sidenav.vue
rocksolid-fe/vue-project/src/router/index.js
rocksolid-fe/vue-project/src/views/EditProfileView.vue

ROC-58 Edit logged in user

---

rocksolid-be/src/main/java/com/rocksolid/config/JwtService.java
rocksolid-fe/vue-project/package-lock.json
rocksolid-fe/vue-project/package.json
rocksolid-fe/vue-project/src/helper/getRoleFromToken.js
rocksolid-fe/vue-project/src/router/index.js
rocksolid-fe/vue-project/yarn.lock

ROC-60 URL modify - wrong layout

ROC-60 URL modify - wrong layout

---

rocksolid-be/src/main/java/com/rocksolid/controller/ConferenceController.java
rocksolid-be/src/main/java/com/rocksolid/dto/ConferenceResponseDto.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceService.java
rocksolid-be/src/main/java/com/rocksolid/service/ConferenceServiceImpl.java
rocksolid-fe/vue-project/src/data/navBarData.js
rocksolid-fe/vue-project/src/router/index.js
rocksolid-fe/vue-project/src/views/ActiveConferences.vue
rocksolid-fe/vue-project/src/views/ConferenceDetail.vue

ROC 57 Show conference details
